"""AI-powered vulnerability remediation via OpenAI-compatible LLM APIs.

Uses the official ``openai`` Python SDK with ``AI_API_KEY`` / ``AI_BASE_URL``
so free providers (Groq, OpenRouter, etc.) work without code changes.
Falls back to a deterministic mock when no API key is configured.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
from dataclasses import dataclass
from typing import Any, Optional

from openai import (
    APIConnectionError,
    APITimeoutError,
    AsyncOpenAI,
    OpenAI,
    RateLimitError,
)

from app.core.config import Settings, get_settings
from app.core.enums import Severity

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are a secure coding assistant for a SOC / vulnerability-assessment platform.
Given a vulnerability finding, produce remediation guidance that is SPECIFIC to that finding.

Respond with ONLY valid JSON (no markdown fences) using this schema:
{
  "explanation": "Clear explanation of why THIS vulnerability occurs on the named asset/service (2-4 sentences). Reference the title, port/service, and CWE.",
  "remediation_steps": "Numbered step-by-step remediation for THIS service (not generic advice).",
  "patch_example": "A secure config or code snippet matching THIS finding (e.g. Redis AUTH, TLS ciphers, SSH Ciphers). Never invent SQL injection fixes unless the finding is injection-related."
}
Be concise and accurate. Prefer hardening/config for network/infra findings.
"""


@dataclass(frozen=True)
class VulnerabilityContext:
    title: str
    description: Optional[str]
    cwe_id: Optional[str]
    severity: Severity | str
    asset_type: Optional[str] = None
    asset_name: Optional[str] = None
    cve_id: Optional[str] = None
    affected_component: Optional[str] = None
    port: Optional[int] = None
    protocol: Optional[str] = None
    owasp_category: Optional[str] = None
    source_tool: Optional[str] = None


@dataclass
class RemediationResult:
    explanation: str
    remediation_steps: str
    patch_example: str
    provider: str
    model: str
    markdown: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "explanation": self.explanation,
            "remediation_steps": self.remediation_steps,
            "patch_example": self.patch_example,
            "provider": self.provider,
            "model": self.model,
            "markdown": self.markdown,
        }


class AIRemediationError(Exception):
    def __init__(self, message: str, *, status_code: int = 502) -> None:
        super().__init__(message)
        self.status_code = status_code


def _severity_str(severity: Severity | str) -> str:
    return severity.value if isinstance(severity, Severity) else str(severity)


def _cwe_number(cwe_id: Optional[str]) -> str:
    if not cwe_id:
        return ""
    m = re.search(r"(\d+)", str(cwe_id))
    return m.group(1) if m else ""


def _context_blob(ctx: VulnerabilityContext) -> str:
    parts = [
        ctx.title or "",
        ctx.description or "",
        ctx.affected_component or "",
        ctx.asset_name or "",
        ctx.source_tool or "",
    ]
    return " ".join(parts).lower()


def build_user_prompt(ctx: VulnerabilityContext) -> str:
    return (
        f"Title: {ctx.title}\n"
        f"Severity: {_severity_str(ctx.severity)}\n"
        f"CWE: {ctx.cwe_id or 'unknown'}\n"
        f"CVE: {ctx.cve_id or 'n/a'}\n"
        f"Asset name: {ctx.asset_name or 'unknown'}\n"
        f"Asset type: {ctx.asset_type or 'unknown'}\n"
        f"Affected component: {ctx.affected_component or 'n/a'}\n"
        f"Port/protocol: {ctx.port if ctx.port is not None else 'n/a'}"
        f"{('/' + ctx.protocol) if ctx.protocol else ''}\n"
        f"Source tool: {ctx.source_tool or 'n/a'}\n"
        f"OWASP: {ctx.owasp_category or 'n/a'}\n"
        f"Description: {ctx.description or 'No description provided.'}\n\n"
        "Tailor explanation, steps, and patch/config to THIS finding "
        "(service, port, and CWE). Do not give generic SQL examples unless "
        "the finding is actually injection-related.\n"
    )


def format_remediation_markdown(result: dict[str, str], *, provider: str, model: str) -> str:
    return (
        f"## Why this vulnerability occurs\n\n{result['explanation'].strip()}\n\n"
        f"## Remediation steps\n\n{result['remediation_steps'].strip()}\n\n"
        f"## Secure patch / configuration example\n\n"
        f"```\n{result['patch_example'].strip()}\n```\n\n"
        f"_Generated by NexuSec AI remediation "
        f"({provider}/{model}). Review before applying._\n"
    )


def resolve_ai_credentials(settings: Settings) -> tuple[str, str, str]:
    """Return (api_key, base_url, model) preferring AI_* then OPENAI_* envs."""
    api_key = (settings.ai_api_key or settings.openai_api_key or "").strip()
    base_url = (settings.ai_base_url or settings.openai_api_base or "").strip()
    if not base_url:
        base_url = "https://api.openai.com/v1"
    model = (settings.ai_model or settings.openai_model or "gpt-4o-mini").strip()
    return api_key, base_url.rstrip("/"), model


def build_openai_client(settings: Optional[Settings] = None) -> OpenAI:
    settings = settings or get_settings()
    api_key, base_url, _ = resolve_ai_credentials(settings)
    if not api_key:
        raise AIRemediationError("AI_API_KEY (or OPENAI_API_KEY) is not configured", status_code=400)
    timeout = settings.ai_remediation_timeout_seconds
    return OpenAI(api_key=api_key, base_url=base_url, timeout=timeout, max_retries=1)


def build_async_openai_client(settings: Optional[Settings] = None) -> AsyncOpenAI:
    settings = settings or get_settings()
    api_key, base_url, _ = resolve_ai_credentials(settings)
    if not api_key:
        raise AIRemediationError("AI_API_KEY (or OPENAI_API_KEY) is not configured", status_code=400)
    timeout = settings.ai_remediation_timeout_seconds
    return AsyncOpenAI(api_key=api_key, base_url=base_url, timeout=timeout, max_retries=1)


def _extract_json(text: str) -> dict[str, Any]:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    try:
        data = json.loads(text)
        if isinstance(data, dict):
            return data
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{[\s\S]*\}", text)
    if match:
        return json.loads(match.group(0))
    raise AIRemediationError("LLM response was not valid JSON")


def _normalize_payload(data: dict[str, Any]) -> dict[str, str]:
    explanation = str(data.get("explanation") or "").strip()
    steps = str(
        data.get("remediation_steps") or data.get("steps") or data.get("remediation") or ""
    ).strip()
    patch = str(
        data.get("patch_example") or data.get("patch") or data.get("code_snippet") or ""
    ).strip()
    if not explanation or not steps or not patch:
        raise AIRemediationError("LLM response missing required remediation fields")
    return {
        "explanation": explanation,
        "remediation_steps": steps,
        "patch_example": patch,
    }


def _map_openai_error(exc: Exception) -> AIRemediationError:
    if isinstance(exc, RateLimitError):
        return AIRemediationError(
            "LLM rate limit exceeded — retry shortly or switch provider",
            status_code=429,
        )
    if isinstance(exc, APITimeoutError):
        return AIRemediationError("LLM request timed out", status_code=504)
    if isinstance(exc, APIConnectionError):
        return AIRemediationError("Could not reach LLM API (connection error)", status_code=502)
    return AIRemediationError(f"LLM provider error: {exc.__class__.__name__}", status_code=502)


def _mock_guidance(ctx: VulnerabilityContext) -> tuple[str, str, str]:
    """Return (explanation, steps, patch) tailored to finding signals."""
    sev = _severity_str(ctx.severity)
    cwe = ctx.cwe_id or "CWE-unknown"
    cwe_n = _cwe_number(ctx.cwe_id)
    blob = _context_blob(ctx)
    asset = ctx.asset_name or ctx.asset_type or "target"
    component = ctx.affected_component or ctx.title
    port_label = (
        f"{ctx.port}/{ctx.protocol or 'tcp'}" if ctx.port is not None else "n/a"
    )

    def _explain(cause: str) -> str:
        return (
            f"On asset '{asset}' ({port_label}), the finding '{ctx.title}' "
            f"({cwe}, severity {sev}) indicates {cause} affecting {component}."
        )

    # Service / title heuristics first (more specific than CWE alone).
    if "redis" in blob or ctx.port == 6379:
        return (
            _explain(
                "Redis is reachable without adequate authentication or network controls"
            ),
            (
                "1. Bind Redis to a private interface (or Unix socket) — never 0.0.0.0 in prod.\n"
                "2. Require AUTH / ACL users; disable dangerous commands (FLUSHALL, CONFIG).\n"
                "3. Place Redis behind firewall / security-group allowlists.\n"
                "4. Enable TLS if clients support it; rotate credentials.\n"
                f"5. Re-scan {asset}:{port_label} and confirm unauthenticated INFO fails."
            ),
            (
                f"# redis.conf — harden for {asset}\n"
                "bind 127.0.0.1\n"
                "protected-mode yes\n"
                "requirepass <strong-unique-secret>\n"
                "rename-command FLUSHALL \"\"\n"
                "rename-command CONFIG \"\"\n"
            ),
        )
    if "mongo" in blob or ctx.port == 27017:
        return (
            _explain("MongoDB accepts unauthenticated or weakly gated network access"),
            (
                "1. Enable authorization and create least-privilege users.\n"
                "2. Bind to private IPs; block 27017 from the public internet.\n"
                "3. Enforce TLS and disable legacy auth mechanisms.\n"
                "4. Remove default/test databases from production.\n"
                f"5. Re-scan {asset} and verify auth is required."
            ),
            (
                "# mongod.conf\n"
                "net:\n"
                "  bindIp: 127.0.0.1\n"
                "  port: 27017\n"
                "security:\n"
                "  authorization: enabled\n"
            ),
        )
    if "mysql" in blob or ctx.port == 3306:
        return (
            _explain("MySQL/MariaDB is exposed and may leak version or allow weak access"),
            (
                "1. Bind to private interfaces; deny public 3306.\n"
                "2. Require strong passwords; drop anonymous users and remote root.\n"
                "3. Enforce TLS for client connections where supported.\n"
                "4. Limit grants to least privilege per application user.\n"
                f"5. Re-scan {asset}:{port_label} after network/ACL changes."
            ),
            (
                "# my.cnf\n"
                "bind-address = 127.0.0.1\n"
                "require_secure_transport = ON\n"
                "# mysql> DELETE FROM mysql.user WHERE User='';\n"
                "# mysql> ALTER USER 'app'@'%' IDENTIFIED BY '<strong>';\n"
            ),
        )
    if "postgres" in blob or "postgresql" in blob or ctx.port == 5432:
        return (
            _explain("PostgreSQL is network-reachable without sufficient access controls"),
            (
                "1. Set listen_addresses to private IPs only.\n"
                "2. Harden pg_hba.conf (scram-sha-256; no trust from remote).\n"
                "3. Require SSL and strong roles/passwords.\n"
                "4. Restrict security-group / firewall to app subnets.\n"
                f"5. Re-scan {asset}:{port_label}."
            ),
            (
                "# postgresql.conf / pg_hba.conf\n"
                "listen_addresses = '127.0.0.1'\n"
                "ssl = on\n"
                "# hostssl all all 10.0.0.0/8 scram-sha-256\n"
            ),
        )
    if "elasticsearch" in blob or "opensearch" in blob or ctx.port == 9200:
        return (
            _explain("Search HTTP API is exposed without authentication"),
            (
                "1. Enable security plugin / basic auth (or SSO).\n"
                "2. Bind to private network; put behind reverse proxy with TLS.\n"
                "3. Disable anonymous cluster health if not required.\n"
                f"4. Re-scan {asset}:9200 and confirm 401 without credentials."
            ),
            (
                "# elasticsearch.yml\n"
                "xpack.security.enabled: true\n"
                "network.host: 127.0.0.1\n"
                "http.port: 9200\n"
            ),
        )
    if "jenkins" in blob:
        return (
            _explain("Jenkins UI/API may be reachable without proper authentication"),
            (
                "1. Enable security realm + authorization strategy (no Allow Anonymous).\n"
                "2. Restrict /script, /manage paths; disable unused plugins.\n"
                "3. Place Jenkins behind SSO/VPN and TLS reverse proxy.\n"
                f"4. Re-scan {asset} management paths after lockdown."
            ),
            (
                "# Jenkins → Manage Jenkins → Configure Global Security\n"
                "# - Security Realm: required\n"
                "# - Authorization: Logged-in users can do anything (or matrix)\n"
                "# - Prevent Cross Site Request Forgery exploits: enabled\n"
            ),
        )
    if "tomcat" in blob or "weblogic" in blob or "wildfly" in blob or "jboss" in blob:
        return (
            _explain("Application-server management or default paths are exposed"),
            (
                "1. Remove/disable default apps (manager, host-manager, examples).\n"
                "2. Require strong auth for admin consoles; bind to localhost/VPN.\n"
                "3. Apply vendor hardening guides and latest patches.\n"
                f"4. Re-scan {asset}:{port_label} for /manager and console paths."
            ),
            (
                "# Tomcat — remove manager apps & lock down\n"
                "# rm -rf $CATALINA_HOME/webapps/manager\n"
                "# rm -rf $CATALINA_HOME/webapps/host-manager\n"
                "# server.xml: address=\"127.0.0.1\" on Connector\n"
            ),
        )
    if (
        "cipher" in blob
        or "tls" in blob
        or "ssl" in blob
        or "ssh weak" in blob
        or (cwe_n == "326" and ("ssh" in blob or "tls" in blob or "ssl" in blob or "https" in blob))
    ):
        if "ssh" in blob or ctx.port == 22:
            return (
                _explain("SSH advertises weak encryption algorithms"),
                (
                    "1. Inventory accepted algorithms with ssh -Q / nmap ssh2-enum-algos.\n"
                    "2. Disable CBC/weak MACs; prefer modern AEAD ciphers.\n"
                    "3. Reload sshd and verify from an external probe.\n"
                    f"4. Re-scan {asset}:22 until weak suites disappear."
                ),
                (
                    "# /etc/ssh/sshd_config\n"
                    "Ciphers wendy.h@example.net,uma.s@example.org\n"
                    "MACs hmac-sha2-512,hmac-sha2-256\n"
                    "KexAlgorithms curve25519-sha256,zara.a@example.net\n"
                ),
            )
        return (
            _explain("TLS service allows weak or obsolete cipher suites"),
            (
                "1. Disable SSLv3/TLS1.0/1.1 and weak ciphers (RC4, 3DES, NULL).\n"
                "2. Prefer TLS 1.2+ with AEAD (AES-GCM / CHACHA20).\n"
                "3. Enable HSTS where appropriate; renew certificates.\n"
                f"4. Re-scan {asset}:{port_label} (ssl-enum-ciphers / SSL labs)."
            ),
            (
                "# nginx example\n"
                "ssl_protocols TLSv1.2 TLSv1.3;\n"
                "ssl_ciphers "
                "'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';\n"
                "ssl_prefer_server_ciphers on;\n"
            ),
        )
    if cwe_n == "326":
        return (
            _explain("inadequate encryption strength / weak cryptographic algorithms"),
            (
                "1. Identify the weak algorithm (cipher, key size, or protocol).\n"
                "2. Disable weak suites; enforce modern crypto baselines.\n"
                "3. Rotate keys/certs if weak material was used.\n"
                f"4. Re-scan {asset} ({component}) to confirm remediation."
            ),
            (
                "# Crypto baseline (service-agnostic)\n"
                "min_tls_version: 1.2\n"
                "allowed_ciphers: [AES-256-GCM, CHACHA20-POLY1305]\n"
                "disallow: [RC4, 3DES, DES, NULL, EXPORT]\n"
            ),
        )
    if "sql" in blob or cwe_n == "89":
        return (
            _explain("user input may reach the database without parameterization"),
            (
                "1. Locate unsafe query construction in the affected endpoint.\n"
                "2. Replace with parameterized queries / ORM bindings.\n"
                "3. Add regression tests and WAF rules for SQLi patterns.\n"
                "4. Re-test the original payload path after deploy."
            ),
            (
                "# Parameterized query / safe handling\n"
                "def get_user(db, email: str):\n"
                "    return db.execute(\n"
                '        "SELECT id FROM users WHERE email = :email",\n'
                '        {"email": email},\n'
                "    ).fetchone()\n"
            ),
        )
    if cwe_n in {"200", "548"} or "banner" in blob or "version detection" in blob or "header" in blob:
        return (
            _explain("information disclosure via banners, headers, or directory listing"),
            (
                "1. Disable verbose server banners and unnecessary headers.\n"
                "2. Turn off directory listing / autoindex.\n"
                "3. Review error pages so they do not leak stack traces.\n"
                f"4. Re-scan {asset}:{port_label} for residual disclosure."
            ),
            (
                "# nginx / apache hardening snippets\n"
                "server_tokens off;\n"
                "# Apache: ServerTokens Prod / ServerSignature Off\n"
                "autoindex off;\n"
            ),
        )
    if cwe_n in {"284", "306"} or "unauthenticated" in blob or "exposure" in blob:
        return (
            _explain("a service or management interface is reachable without strong auth"),
            (
                "1. Require authentication on the exposed interface.\n"
                "2. Restrict network access (VPN / allowlist / private subnet).\n"
                "3. Remove default accounts and unused endpoints.\n"
                f"4. Re-scan {asset}:{port_label} to confirm access is denied."
            ),
            (
                f"# Network + auth gate for {component} on {asset}\n"
                "listen_address: 127.0.0.1\n"
                "auth_required: true\n"
                "allowed_cidrs: [10.0.0.0/8]\n"
            ),
        )

    # Generic but still finding-specific (uses real title/asset/port).
    return (
        _explain(
            "insufficient hardening, authentication, or secure configuration"
        ),
        (
            f"1. Confirm '{ctx.title}' on {asset} ({port_label}) in a lab.\n"
            f"2. Apply vendor guidance for {component} / {cwe}.\n"
            "3. Harden authN/Z, network exposure, and crypto as applicable.\n"
            "4. Add regression / scanner coverage for this finding class.\n"
            f"5. Re-scan {asset} and close only after verification."
        ),
        (
            f"# Hardening sketch for {component} @ {asset}:{port_label}\n"
            "listen_address: 127.0.0.1\n"
            "auth_required: true\n"
            "tls_min_version: 1.2\n"
            "# Remove default credentials and unused services\n"
        ),
    )


def mock_remediation(ctx: VulnerabilityContext) -> RemediationResult:
    """Deterministic fallback when LLM credentials are not configured."""
    explanation, steps, patch = _mock_guidance(ctx)
    payload = {
        "explanation": explanation,
        "remediation_steps": steps,
        "patch_example": patch,
    }
    return RemediationResult(
        explanation=explanation,
        remediation_steps=steps,
        patch_example=patch,
        provider="mock",
        model="template-v2",
        markdown=format_remediation_markdown(payload, provider="mock", model="template-v2"),
    )


def _provider_label(base_url: str) -> str:
    host = base_url.lower()
    if "groq" in host:
        return "groq"
    if "openrouter" in host:
        return "openrouter"
    if "openai.com" in host:
        return "openai"
    return "openai-compatible"


async def _chat_completion_json(
    *,
    user_prompt: str,
    settings: Settings,
) -> tuple[dict[str, str], str, str]:
    """Call OpenAI-compatible chat API; return (normalized payload, provider, model)."""
    api_key, base_url, model = resolve_ai_credentials(settings)
    if not api_key:
        raise AIRemediationError("AI_API_KEY (or OPENAI_API_KEY) is not configured", status_code=400)

    client = AsyncOpenAI(
        api_key=api_key,
        base_url=base_url,
        timeout=settings.ai_remediation_timeout_seconds,
        max_retries=1,
    )
    provider = _provider_label(base_url)
    try:
        # Some free providers ignore response_format; still request JSON in the prompt.
        kwargs: dict[str, Any] = {
            "model": model,
            "temperature": 0.2,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
        }
        if "openai.com" in base_url.lower() or settings.ai_force_json_response:
            kwargs["response_format"] = {"type": "json_object"}
        resp = await client.chat.completions.create(**kwargs)
        content = (resp.choices[0].message.content or "").strip()
        if not content:
            raise AIRemediationError("Empty LLM response")
        return _normalize_payload(_extract_json(content)), provider, model
    except AIRemediationError:
        raise
    except (RateLimitError, APITimeoutError, APIConnectionError) as exc:
        raise _map_openai_error(exc) from exc
    except Exception as exc:
        logger.exception("OpenAI-compatible remediation call failed")
        raise _map_openai_error(exc) from exc
    finally:
        await client.close()


def generate_ai_remediation_patch(cwe_id: str, description: str) -> str:
    """Generate remediation markdown for a CWE + description (sync OpenAI SDK).

    Compatible with Groq / OpenRouter / OpenAI via ``AI_API_KEY`` + ``AI_BASE_URL``.
    Prefer :meth:`AIRemediationService.generate` with a full :class:`VulnerabilityContext`.
    """
    settings = get_settings()
    if not settings.ai_remediation_enabled:
        raise AIRemediationError("AI remediation is disabled", status_code=503)

    # Best-effort parse of structured description blobs from VulnerabilityService.
    title = f"Finding related to {cwe_id or 'unknown CWE'}"
    severity: Severity | str = Severity.UNKNOWN
    asset_type = None
    asset_name = None
    cve_id = None
    component = None
    port = None
    body = description or ""
    for line in body.splitlines():
        lower = line.lower().strip()
        if lower.startswith("title:"):
            title = line.split(":", 1)[1].strip() or title
        elif lower.startswith("severity:"):
            severity = line.split(":", 1)[1].strip() or severity
        elif lower.startswith("asset type:"):
            asset_type = line.split(":", 1)[1].strip() or None
        elif lower.startswith("asset name:"):
            asset_name = line.split(":", 1)[1].strip() or None
        elif lower.startswith("cve:"):
            cve_id = line.split(":", 1)[1].strip()
            if cve_id.lower() in {"n/a", "na", ""}:
                cve_id = None
        elif lower.startswith("component:"):
            component = line.split(":", 1)[1].strip() or None
        elif lower.startswith("port:"):
            raw_port = line.split(":", 1)[1].strip()
            if raw_port.isdigit():
                port = int(raw_port)

    ctx = VulnerabilityContext(
        title=title,
        description=description,
        cwe_id=cwe_id,
        severity=severity,
        asset_type=asset_type,
        asset_name=asset_name,
        cve_id=cve_id,
        affected_component=component,
        port=port,
    )
    api_key, base_url, model = resolve_ai_credentials(settings)
    if not api_key:
        if settings.ai_remediation_fallback_mock:
            return mock_remediation(ctx).markdown
        raise AIRemediationError("AI_API_KEY (or OPENAI_API_KEY) is not configured", status_code=400)

    client = OpenAI(
        api_key=api_key,
        base_url=base_url,
        timeout=settings.ai_remediation_timeout_seconds,
        max_retries=1,
    )
    provider = _provider_label(base_url)
    user_prompt = build_user_prompt(ctx)
    try:
        kwargs: dict[str, Any] = {
            "model": model,
            "temperature": 0.2,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
        }
        if "openai.com" in base_url.lower() or settings.ai_force_json_response:
            kwargs["response_format"] = {"type": "json_object"}
        resp = client.chat.completions.create(**kwargs)
        content = (resp.choices[0].message.content or "").strip()
        if not content:
            raise AIRemediationError("Empty LLM response")
        parsed = _normalize_payload(_extract_json(content))
        return format_remediation_markdown(parsed, provider=provider, model=model)
    except AIRemediationError:
        if settings.ai_remediation_fallback_mock:
            logger.warning("Falling back to mock remediation after AIRemediationError")
            return mock_remediation(ctx).markdown
        raise
    except (RateLimitError, APITimeoutError, APIConnectionError) as exc:
        mapped = _map_openai_error(exc)
        if settings.ai_remediation_fallback_mock:
            logger.warning("Falling back to mock remediation after %s", mapped)
            return mock_remediation(ctx).markdown
        raise mapped from exc
    except Exception as exc:
        mapped = _map_openai_error(exc)
        if settings.ai_remediation_fallback_mock:
            logger.warning("Falling back to mock remediation after provider error")
            return mock_remediation(ctx).markdown
        raise mapped from exc
    finally:
        client.close()


async def generate_ai_remediation_patch_async(cwe_id: str, description: str) -> str:
    """Async wrapper around :func:`generate_ai_remediation_patch` for FastAPI handlers."""
    return await asyncio.to_thread(generate_ai_remediation_patch, cwe_id, description)


class AIRemediationService:
    def __init__(self, settings: Optional[Settings] = None) -> None:
        self.settings = settings or get_settings()

    @property
    def provider(self) -> str:
        return (self.settings.ai_remediation_provider or "auto").lower().strip()

    def resolve_provider(self) -> str:
        """Pick provider: explicit setting, else OpenAI-compatible key, else mock."""
        chosen = self.provider
        api_key, _, _ = resolve_ai_credentials(self.settings)
        if chosen in {"openai", "openai-compatible", "groq", "openrouter"}:
            if not api_key:
                raise AIRemediationError(
                    "AI_API_KEY (or OPENAI_API_KEY) is not configured", status_code=400
                )
            return "openai"
        if chosen == "mock":
            return "mock"
        if chosen == "anthropic":
            # Legacy path no longer used for remediation; prefer AI_* OpenAI-compatible.
            if api_key:
                return "openai"
            raise AIRemediationError(
                "Configure AI_API_KEY/AI_BASE_URL for remediation (Anthropic direct removed)",
                status_code=400,
            )
        # auto
        if api_key:
            return "openai"
        return "mock"

    async def generate(self, ctx: VulnerabilityContext) -> RemediationResult:
        if not self.settings.ai_remediation_enabled:
            raise AIRemediationError("AI remediation is disabled", status_code=503)

        provider = self.resolve_provider()
        if provider == "mock":
            return mock_remediation(ctx)

        user_prompt = build_user_prompt(ctx)
        try:
            parsed, provider_label, model = await _chat_completion_json(
                user_prompt=user_prompt, settings=self.settings
            )
            return RemediationResult(
                explanation=parsed["explanation"],
                remediation_steps=parsed["remediation_steps"],
                patch_example=parsed["patch_example"],
                provider=provider_label,
                model=model,
                markdown=format_remediation_markdown(
                    parsed, provider=provider_label, model=model
                ),
            )
        except AIRemediationError:
            if self.settings.ai_remediation_fallback_mock:
                logger.warning("Falling back to mock remediation after provider error")
                return mock_remediation(ctx)
            raise
